// Injects shared single-source fragments into the hand-written static pages
// (the ones the generators do not emit): the canonical/OpenGraph/Twitter meta
// block, the Organization JSON-LD and the standard footer. Content comes from
// scripts/lib/* so there is still one source of truth; this script only places
// it. Re-running replaces the blocks in place (idempotent).

import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { organizationJsonLd } from "./lib/site-schema.mjs";
import { footerHtml, metaTagsHtml } from "./lib/site-content.mjs";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const HEAD_BEGIN = "<!-- BEGIN: unique-analyse-head -->";
const HEAD_END = "<!-- END: unique-analyse-head -->";
// Legacy marker from the first schema-only pass — stripped on migration.
const LEGACY_BEGIN = "<!-- BEGIN: unique-analyse-org-schema -->";
const LEGACY_END = "<!-- END: unique-analyse-org-schema -->";

// Legacy English duplicates → canonical points at the live Turkish page.
const CANONICAL_OVERRIDE = {
  "about.html": "/hakkimizda/",
  "contact.html": "/iletisim/",
  "europe.html": "/avrupa/",
  "services.html": "/hizmetler/",
  "reports.html": "/raporlar/"
};

const findHtmlFiles = async (dir) => {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    if (entry.name === "node_modules" || entry.name.startsWith(".")) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) files.push(...(await findHtmlFiles(full)));
    else if (entry.name.endsWith(".html")) files.push(full);
  }
  return files;
};

const decodeEntities = (value = "") =>
  value
    .replaceAll("&quot;", '"')
    .replaceAll("&lt;", "<")
    .replaceAll("&gt;", ">")
    .replaceAll("&amp;", "&")
    .trim();

const canonicalForFile = (rel) => {
  if (CANONICAL_OVERRIDE[rel]) return CANONICAL_OVERRIDE[rel];
  if (rel === "index.html") return "/";
  if (rel.endsWith("/index.html")) return `/${rel.slice(0, -"index.html".length)}`;
  return `/${rel}`;
};

const stripBlock = (html, begin, end) => {
  const re = new RegExp(`[ \\t]*${begin}[\\s\\S]*?${end}\\n?`, "g");
  return html.replace(re, "");
};

const files = await findHtmlFiles(rootDir);
let injected = 0;
let skipped = 0;

for (const file of files) {
  let html = await readFile(file, "utf8");

  // Generated pages already carry these fragments from their generator.
  if (html.includes("Generated by scripts/")) {
    skipped += 1;
    continue;
  }
  if (!html.includes("</head>") || !html.includes("<title>")) {
    skipped += 1;
    continue;
  }

  const rel = path.relative(rootDir, file);
  const title = decodeEntities((html.match(/<title>([\s\S]*?)<\/title>/) || [, ""])[1]);
  const description = decodeEntities(
    (html.match(/name="description"[\s\S]*?content="([\s\S]*?)"/i) || [, ""])[1]
  );
  const canonicalPath = canonicalForFile(rel);

  const headBlock = [
    `    ${HEAD_BEGIN}`,
    metaTagsHtml({ canonicalPath, title, description }, 4),
    organizationJsonLd(4),
    `    ${HEAD_END}`
  ].join("\n");

  // Remove previous head/legacy blocks, then insert fresh before </head>.
  html = stripBlock(html, HEAD_BEGIN, HEAD_END);
  html = stripBlock(html, LEGACY_BEGIN, LEGACY_END);
  html = html.replace(/([ \t]*)<\/head>/, `${headBlock}\n$1</head>`);

  // Replace the footer with the shared single-source footer.
  html = html.replace(
    /([ \t]*)<footer class="site-footer">[\s\S]*?<\/footer>/,
    (match, indentStr) => footerHtml(indentStr.length)
  );

  await writeFile(file, html, "utf8");
  injected += 1;
  console.log(`- ${rel}`);
}

console.log(`\nInjected meta+schema+footer into ${injected} static page(s); skipped ${skipped}.`);
